import { Heading, Box, Image, Text, Center, Stack, useBreakpointValue, Spacer } from "@chakra-ui/react"
import SimpleSearch from "../search/SimpleSearch"
import BuyMeACoffee from "../social/BuyMeACoffee"

const Main = () => {
    return(
        <div>
            <Heading fontSize={{ base: '4xl', md: '5xl', lg: '5xl' }}>
                <Center>
                <Box w={{ base: "100%", sm: "60%", md: "50%" }} maxWidth={150} mb={{ base: 12, md: 0, sm: 0 }}>
                    <Image src='/icetea-bw.svg'/>
                </Box>
                <Text
                as={'span'}
                position={'relative'}
                _after={{
                    content: "''",
                    width: 'full',
                    height: useBreakpointValue({ base: '20%', md: '30%' }),
                    position: 'absolute',
                    bottom: 1,
                    left: 0,
                    bg: 'blue.400',
                    zIndex: -1,
                }}>
                Cocktail Hour
                </Text>
                </Center>
                <br />
                {' '}
                <Text color={'blue.400'} fontSize={{ base: '2xl', md: '1xl', lg: '1xl' }} textAlign='center'>
                    Sip on a uniquely crafted drink, generated by A.I., that will complete your next album listen-along or event
                </Text>
                <br />
                {' '}
            </Heading>
            <Text fontSize={{ base: 'md', lg: 'lg' }} color={'gray.500'} textAlign='center'>
                It's simple. Enter a favorite artist, album, life event, or mood and we'll try to generate something unique for the occasion.
            </Text>
            <br />
            <Stack direction={{ base: 'column', md: 'row' }} spacing={4}>
                <SimpleSearch />
            </Stack>
        </div>
    )
}

export default Main