styles = {
    'pop': 'blend',
    'rock': 'strong',
    'hip hop': 'fizz',
    'rap': 'sour',
    'electronic': 'complex',
    'folk': 'basic',
    'jazz': 'sour',
    'country': 'basic',
    'indie': 'smash',
    'alternative': 'sour',
    'art': 'complex',
    'metal': 'strong',
    'classical': 'basic',
    'reggae': 'smash',
    'house': 'complex',
    'dance': 'fizz',
    'latin': 'sour',
    'soul': 'strong',
    'blues': 'strong',
    'emo': 'smash',
    'punk': 'complex',
    'funk': 'smash',
    'disco': 'fizz',
    'reggaeton': 'smash',
    'rockabilly': 'strong',
    'ska': 'smash',
    'fruit': 'smash',
    'basic': 'basic',
    'sour': 'sour',
    'intense': 'strong',
    'bubble': 'fizz',
    'complex': 'complex',
    'blend': 'blend',
    'smash': 'smash',
    'neat': 'neat'
}